version: '3'

services: 
  spark-master:
    image: bitnami/spark:latest
    environment: 
      - SPARK_MODE=master
    volumes: 
      - spark-volumes:/bitnami/spark
      - ./test:/opt/bitnami/spark/test
    ports: 
      - 7070:7070
      - 8080:8080

  spark-worker-1:
    image: bitnami/spark:latest
    volumes:
      - spark-volumes:/bitnami/spark
      - ./test:/opt/bitnami/spark/test
    environment: 
      - SPARK_MODE=worker
      - SPARK_MASTER=spark://spark-master:7070


volumes:
  spark-volumes: